# Generated by Django 3.2.5 on 2022-09-13 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_post_likes', to='network.post')),
                ('userLike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_user_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
